# Spring Boot application configuration
spring:
  application:
    name: query-api-service
  profiles:
    active: dev # Default profile

  # Jackson Deserialization fail on unknown properties - false (good for DTOs)
  jackson:
    deserialization:
      fail-on-unknown-properties: false

  # --- Datasource Configuration for Metadata (Primary Datasource) ---
  # This will be used by Spring Data JPA for DataSourceConfigEntity, SqlTemplateEntity etc.
  datasource:
    url: jdbc:mysql://localhost:3306/query_api_metadata?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root # Replace with your metadata DB username
    password: password # Replace with your metadata DB password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: HikariPool-Metadata
      maximumPoolSize: 10
      minimumIdle: 2
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000

  # --- JPA Configuration for Metadata ---
  jpa:
    hibernate:
      ddl-auto: update # In dev, `update` is fine. For prod, use `validate` or Flyway/Liquibase.
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect # Or org.hibernate.dialect.OceanBaseDialect if using OceanBase
      hibernate.format_sql: true

# --- MyBatis Configuration (primarily for dynamic datasources) ---
# The default SqlSessionFactory will use the primary datasource above.
# Dynamic datasource switching for MyBatis is handled in QueryExecutionServiceImpl.
mybatis:
  mapper-locations: classpath*:mybatis-mappers/**/*.xml # Location of MyBatis XML mapper files if any
  configuration:
    map-underscore-to-camel-case: true
    # Other MyBatis global configurations

# --- Server Configuration ---
server:
  port: 8080
  servlet:
    context-path: /query-api

# --- Springdoc OpenAPI (Swagger UI) Configuration ---
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operations-sorter: alpha
    tags-sorter: alpha

# --- Logging Configuration (Example for console) ---
logging:
  level:
    root: INFO
    com.example.queryapi: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG # To see SQL queries generated by Hibernate
    org.hibernate.type.descriptor.sql: TRACE # To see parameters for Hibernate queries
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# --- Actuator Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics,loggers,env,configprops,beans,mappings"
  endpoint:
    health:
      show-details: always

# --- Custom Application Properties (if any) ---
# app:
#   some-property: value

